### ISSUE TITLE
I accidentally donated a UUID, how do I get it back?

### ISSUE THREAD

**Issue by moswald** [reuuid/reuuid-howto#1]
I accidentally donated `6eb19fa9-320f-4480-b2d8-7948d371d9ba`, but that was an accident, as it's still being used. How can I get it back? There should be an undo.

Urgent, please reply.

**Comment by Solumin** [comment]
Sorry, but I'm pretty sure the main donation page says "all donations are final." The developer might be able to help you though.

**Comment by reuuid** [comment]
Sorry for the late replies.  I've marked the UUID in the database as taken.  Feel free to keep on using it.
